### ISSUE TITLE
Return $record for addRecord method is null

### ISSUE THREAD

**Issue by kjavitz** [cristianpontes/zoho-crm-client-php#17]
Hi,

I am getting null for when I try and return the $record after using the addRecord method, sample:

`$client = new ZohoCRMClient('Leads', 'xxx');`

`$record = $client->insertRecords()
    ->addRecord([
            'First Name' => "test1",
            'Last Name' => "test2",
            'Email' => 'test83383385@gmail.com',
            'Company' => 'Test Compt',
            'Phone' =>  '34324323434',
            'Lead Source' => 'Free Trial',
            'Lead Owner' => 'ttest89@gmail.com'
        ])->request();`

`echo "<pre>";
var_dump($record);
echo "</pre>";`

The expected behavior would be to return the $record info so I can get the $record id using $record->id but it comes back as null. The record is inserted fine to the leads section of Zoho.

**Comment by gblair** [comment]
@cristianpontes I wonder if this is related to https://github.com/cristianpontes/zoho-crm-client-php/blob/b88e39e8f0826d2b73552a63ec430d02934af95b/Request/UpdateRecords.php#L98-L100

It seems that change has broken the `parse` results in `\CristianPontes\ZohoCRMClient\Transport\XmlDataTransportDecorator::parse` for me, because with API version 2 the results come back in a different format 😦  than is expected there.

@kjavitz which version of this package are you using?

**Comment by cristianpontes** [comment]
@gblair You are right, I didn't take into consideration that. 

I did a hotfix and a minor release 1.6.1 which should solve the problem in the mean time. 

@kjavitz sorry for the inconveniences.
