### ISSUE TITLE
API V2.0 Upgrade

### ISSUE THREAD

**Issue by interwap** [cristianpontes/zoho-crm-client-php#36]
Will there be an api v2.0 upgrade of this piece of software and will it allow other api methods like users etc?

**Comment by darrenkhouston** [comment]
I think this will be very important as they are deprecating the current v1.0 API in December 2018. Any news on if a v2.0 upgrade will happen, or will we need to just use the PHP SDK that Zoho offers?

**Comment by arieltoledo** [comment]
Same question over here @cristianpontes, anyway we can help  ?

**Comment by Derewith** [comment]
@interwap you are trying to make a pull by your own?

**Comment by interwap** [comment]
> @interwap you are trying to make a pull by your own?

not yet, if you have, we can collaborate...

**Comment by cristianpontes** [comment]
Hello Guys. 

Sorry for the inactivity on the repo and thanks for your interest in keeping this project alive. 

Unfortunately, I no longer have the availability to maintain this project nor to work on the necessary changes to make it compatible with the API V2.

I believe that Zoho now has an official PHP SDK that is V2 compatible and it has all the required features. 

I'm planning to deprecate this repo due to the reasons I mentioned before. However, if anyone wishes to help on this project or take the lead on making it V2 compatible, I'm more than happy to add collaborators in this repo. 

Otherwise, feel free fork project and adapt it as you need.

@interwap @darrenkhouston @arieltoledo @Derewith 

Cheers.

**Comment by seekstris** [comment]
Any updates on this? @interwap @Derewith @cristianpontes @arieltoledo

**Comment by arieltoledo** [comment]
@seekstris No updates, I'm using v2 api to insert leads from a contact form just with the sdk provided by Zoho, wich it's really unfriendly by the way.

**Comment by Derewith** [comment]
@seekstris @arieltoledo I'm using v2 api too directly via curl, so this repo is deprecate at this point.

**Comment by seekstris** [comment]
@Derewith Thank you for coming back to this, I'm also using Zoho provided SDK at the moment to insert and convert leads, though my client's website still uses this API along with their custom functions that inserts data in the database while registering on Zoho, is it okay to keep this code just to avoid mishap, along with the zoho sdk.

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favor of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

I want to thank you for using the project and my sincere apologies for any inconveniences

Sincerely,
Cristian
